--- #handlers
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: installing httpd
      action: yum name=httpd state=present
      notify: httpd starting
  handlers:
    - name: httpd starting
      action: service name=httpd state=started
